name: Wine Fedora Fsync CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:42

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compilation
        run: |
          sudo dnf -y -q upgrade --refresh
          cd wine-tkg-git
          ./xiv-staging.sh -fS v10.17
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          sed -i 's/_NOCCACHE=\"\(.*\)\"/_NOCCACHE=\"true\"/' wine-tkg-profiles/advanced-customization.cfg
          yes|./non-makepkg-build.sh

      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-xiv-fedora-fsync
          path: wine-tkg-git/non-makepkg-builds
